/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    characters: Character;
    weapons: Weapon;
    scenarios: Scenario;
    'game-modes': GameMode;
    maps: Map;
    factions: Faction;
    music: Music;
    media: Media;
    tags: Tag;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    characters: CharactersSelect<false> | CharactersSelect<true>;
    weapons: WeaponsSelect<false> | WeaponsSelect<true>;
    scenarios: ScenariosSelect<false> | ScenariosSelect<true>;
    'game-modes': GameModesSelect<false> | GameModesSelect<true>;
    maps: MapsSelect<false> | MapsSelect<true>;
    factions: FactionsSelect<false> | FactionsSelect<true>;
    music: MusicSelect<false> | MusicSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    storyline: Storyline;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    storyline: StorylineSelect<false> | StorylineSelect<true>;
  };
  locale: 'en' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every soul of the CSO world — humans, zombies, bosses and the people in between.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  kind: 'human' | 'zombie' | 'boss' | 'npc';
  classType?: string | null;
  factions?: (number | Faction)[] | null;
  profile?: {
    gender?: string | null;
    age?: string | null;
    height?: string | null;
    weight?: string | null;
    birthplace?: string | null;
    nationality?: string | null;
    birthday?: string | null;
    occupation?: string | null;
    bloodType?: string | null;
  };
  /**
   * The full story — background, motivations, fate.
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  quotes?:
    | {
        text: string;
        context?: string | null;
        id?: string | null;
      }[]
    | null;
  abilities?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  scenarioStats?: {
    health?: number | null;
    attack?: number | null;
    mobility?: number | null;
    armor?: number | null;
    ammo?: number | null;
  };
  costumes?:
    | {
        name: string;
        description?: string | null;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pairing / signature weapon, if the character has one.
   */
  signatureWeapon?: (number | null) | Weapon;
  weapons?: (number | Weapon)[] | null;
  scenarios?: (number | Scenario)[] | null;
  gameModes?: (number | GameMode)[] | null;
  maps?: (number | Map)[] | null;
  relatedCharacters?: (number | Character)[] | null;
  voiceActors?:
    | {
        region: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the interactive viewer on the character page.
   */
  model3d?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  side?: ('ct' | 'tr' | 'zombie' | 'neutral') | null;
  grade?: ('common' | 'rare' | 'unique' | 'epic' | 'transcendent' | 'unknown') | null;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organisations that shaped the war — Aegis, Vanguard, Rex and the rest.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factions".
 */
export interface Faction {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lore?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leaders?: (number | Character)[] | null;
  members?: (number | Character)[] | null;
  emblem?: (number | null) | Media;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  side?: ('ct' | 'tr' | 'zombie' | 'neutral') | null;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  kind:
    | 'icon'
    | 'render'
    | 'portrait'
    | 'artwork'
    | 'screenshot'
    | 'hud'
    | 'minimap'
    | 'audio'
    | 'model-3d'
    | 'video'
    | 'other';
  caption?: string | null;
  /**
   * Artist, uploader or "Nexon"
   */
  credit?: string | null;
  sourceUrl?: string | null;
  license?: ('CC-BY-SA-3.0' | 'fair-use' | 'ai-generated' | 'original') | null;
  aiGeneration?: {
    provider?: string | null;
    model?: string | null;
    prompt?: string | null;
    negativePrompt?: string | null;
    seed?: number | null;
    generatedAt?: string | null;
    referenceImages?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * The armory — from the AK-47 to the Transcendent arsenal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons".
 */
export interface Weapon {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  category:
    | 'pistol'
    | 'shotgun'
    | 'submachine-gun'
    | 'assault-rifle'
    | 'sniper-rifle'
    | 'machine-gun'
    | 'melee'
    | 'grenade'
    | 'equipment'
    | 'special'
    | 'zombie';
  origin?: string | null;
  manufacturer?: string | null;
  caliber?: string | null;
  /**
   * In-game $
   */
  price?: number | null;
  /**
   * e.g. Automatic, Semi-automatic, Shuriken Storm (right-click)
   */
  fireModes?: string[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  obtainMethod?: string | null;
  /**
   * In-game bars, 0–100. Knockback and stun matter in zombie modes.
   */
  stats?: {
    damage?: number | null;
    accuracy?: number | null;
    recoil?: number | null;
    rateOfFire?: number | null;
    /**
     * Higher = slower
     */
    weight?: number | null;
    knockback?: number | null;
    stun?: number | null;
  };
  /**
   * Descriptive notes per stat when the wiki gives prose instead of a bar value, e.g. {"damage": "28 (Normal) / 40-47 (Zombie)"}.
   */
  statNotes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ammo?: {
    magazine?: number | null;
    reserve?: number | null;
    type?: string | null;
  };
  abilities?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reskins, upgrades and sibling weapons.
   */
  variants?: (number | Weapon)[] | null;
  characters?: (number | Character)[] | null;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Side-profile HUD icon (transparent PNG).
   */
  icon?: (number | null) | Media;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  model3d?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  grade?: ('common' | 'rare' | 'unique' | 'epic' | 'transcendent' | 'unknown') | null;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Story chapters — Zombie Scenario seasons and every other narrative campaign.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios".
 */
export interface Scenario {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  gameMode: number | GameMode;
  season?: string | null;
  chapter?: number | null;
  difficulties?: ('easy' | 'normal' | 'hard' | 'very-hard' | 'nightmare' | 'unknown')[] | null;
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objectives?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  rewards?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  bosses?: (number | Character)[] | null;
  characters?: (number | Character)[] | null;
  maps?: (number | Map)[] | null;
  nextChapter?: (number | null) | Scenario;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Each mode tells a different story: Original, Zombie, Scenario, Fun and more.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-modes".
 */
export interface GameMode {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  family: 'original' | 'zombie' | 'scenario' | 'fun' | 'pve' | 'competitive' | 'other';
  maxPlayers?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The story this mode tells.
   */
  lore?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  rules?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps".
 */
export interface Map {
  id: number;
  name: string;
  /**
   * Display name in this locale, if it differs from the canonical name.
   */
  localizedName?: string | null;
  /**
   * Other names, codenames or regional names.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  /**
   * One line that captures the essence.
   */
  tagline?: string | null;
  /**
   * 2–3 sentences for cards and search.
   */
  summary?: string | null;
  /**
   * In-universe location
   */
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gameModes?: (number | GameMode)[] | null;
  scenario?: (number | null) | Scenario;
  minimap?: (number | null) | Media;
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The soundtrack of the world — lobby themes, round music, scenario scores.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music".
 */
export interface Music {
  id: number;
  title: string;
  name?: string | null;
  composer?: string | null;
  album?: string | null;
  durationSeconds?: number | null;
  tagline?: string | null;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audio?: (number | null) | Media;
  usedIn?: {
    gameModes?: (number | GameMode)[] | null;
    scenarios?: (number | Scenario)[] | null;
    maps?: (number | Map)[] | null;
  };
  trivia?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When this appeared in each regional service.
   */
  release?:
    | {
        region: 'kr' | 'cn' | 'tw' | 'jp' | 'id' | 'vn' | 'sg' | 'th' | 'tr' | 'ru' | 'csn';
        date?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Renders, artwork, screenshots. The first image doubles as the hero when no hero is set.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Images/audio hosted on the wiki CDN, pending local ingestion.
   */
  remoteMedia?:
    | {
        url: string;
        kind?:
          | (
              | 'icon'
              | 'render'
              | 'portrait'
              | 'artwork'
              | 'screenshot'
              | 'hud'
              | 'minimap'
              | 'audio'
              | 'model-3d'
              | 'video'
              | 'other'
            )
          | null;
        caption?: string | null;
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL identifier. Auto-generated from the name; edit with care.
   */
  slug: string;
  heroImage?: (number | null) | Media;
  /**
   * Hex colour used to tint this entry’s pages (defaults to the side/grade colour).
   */
  accentColor?: string | null;
  /**
   * Show on the homepage and in featured rails.
   */
  featured?: boolean | null;
  tags?: (number | Tag)[] | null;
  wikiSource?: {
    url?: string | null;
    title?: string | null;
    revisionId?: number | null;
    fetchedAt?: string | null;
    license?: 'CC-BY-SA-3.0' | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'weapons';
        value: number | Weapon;
      } | null)
    | ({
        relationTo: 'scenarios';
        value: number | Scenario;
      } | null)
    | ({
        relationTo: 'game-modes';
        value: number | GameMode;
      } | null)
    | ({
        relationTo: 'maps';
        value: number | Map;
      } | null)
    | ({
        relationTo: 'factions';
        value: number | Faction;
      } | null)
    | ({
        relationTo: 'music';
        value: number | Music;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  kind?: T;
  classType?: T;
  factions?: T;
  profile?:
    | T
    | {
        gender?: T;
        age?: T;
        height?: T;
        weight?: T;
        birthplace?: T;
        nationality?: T;
        birthday?: T;
        occupation?: T;
        bloodType?: T;
      };
  story?: T;
  quotes?:
    | T
    | {
        text?: T;
        context?: T;
        id?: T;
      };
  abilities?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  scenarioStats?:
    | T
    | {
        health?: T;
        attack?: T;
        mobility?: T;
        armor?: T;
        ammo?: T;
      };
  costumes?:
    | T
    | {
        name?: T;
        description?: T;
        imageUrl?: T;
        id?: T;
      };
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  signatureWeapon?: T;
  weapons?: T;
  scenarios?: T;
  gameModes?: T;
  maps?: T;
  relatedCharacters?: T;
  voiceActors?:
    | T
    | {
        region?: T;
        name?: T;
        id?: T;
      };
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  model3d?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  side?: T;
  grade?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weapons_select".
 */
export interface WeaponsSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  category?: T;
  origin?: T;
  manufacturer?: T;
  caliber?: T;
  price?: T;
  fireModes?: T;
  description?: T;
  obtainMethod?: T;
  stats?:
    | T
    | {
        damage?: T;
        accuracy?: T;
        recoil?: T;
        rateOfFire?: T;
        weight?: T;
        knockback?: T;
        stun?: T;
      };
  statNotes?: T;
  ammo?:
    | T
    | {
        magazine?: T;
        reserve?: T;
        type?: T;
      };
  abilities?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  variants?: T;
  characters?: T;
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  icon?: T;
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  model3d?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  grade?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scenarios_select".
 */
export interface ScenariosSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  gameMode?: T;
  season?: T;
  chapter?: T;
  difficulties?: T;
  story?: T;
  objectives?:
    | T
    | {
        text?: T;
        id?: T;
      };
  rewards?:
    | T
    | {
        text?: T;
        id?: T;
      };
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  bosses?: T;
  characters?: T;
  maps?: T;
  nextChapter?: T;
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "game-modes_select".
 */
export interface GameModesSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  family?: T;
  maxPlayers?: T;
  description?: T;
  lore?: T;
  rules?:
    | T
    | {
        text?: T;
        id?: T;
      };
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  slug?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps_select".
 */
export interface MapsSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  location?: T;
  description?: T;
  gameModes?: T;
  scenario?: T;
  minimap?: T;
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  slug?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "factions_select".
 */
export interface FactionsSelect<T extends boolean = true> {
  name?: T;
  localizedName?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  tagline?: T;
  summary?: T;
  description?: T;
  lore?: T;
  leaders?: T;
  members?: T;
  emblem?: T;
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  slug?: T;
  side?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music_select".
 */
export interface MusicSelect<T extends boolean = true> {
  title?: T;
  name?: T;
  composer?: T;
  album?: T;
  durationSeconds?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  audio?: T;
  usedIn?:
    | T
    | {
        gameModes?: T;
        scenarios?: T;
        maps?: T;
      };
  trivia?:
    | T
    | {
        text?: T;
        id?: T;
      };
  release?:
    | T
    | {
        region?: T;
        date?: T;
        note?: T;
        id?: T;
      };
  gallery?: T;
  remoteMedia?:
    | T
    | {
        url?: T;
        kind?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  slug?: T;
  heroImage?: T;
  accentColor?: T;
  featured?: T;
  tags?: T;
  wikiSource?:
    | T
    | {
        url?: T;
        title?: T;
        revisionId?: T;
        fetchedAt?: T;
        license?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  kind?: T;
  caption?: T;
  credit?: T;
  sourceUrl?: T;
  license?: T;
  aiGeneration?:
    | T
    | {
        provider?: T;
        model?: T;
        prompt?: T;
        negativePrompt?: T;
        seed?: T;
        generatedAt?: T;
        referenceImages?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  endOfService?: {
    date?: string | null;
    message?: string | null;
  };
  attribution?: string | null;
  social?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    background?: (number | null) | Media;
  };
  featuredCharacters?: (number | Character)[] | null;
  featuredWeapons?: (number | Weapon)[] | null;
  featuredScenarios?: (number | Scenario)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storyline".
 */
export interface Storyline {
  id: number;
  title?: string | null;
  intro?: string | null;
  eras?:
    | {
        title: string;
        period?: string | null;
        subtitle?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        characters?: (number | Character)[] | null;
        scenarios?: (number | Scenario)[] | null;
        factions?: (number | Faction)[] | null;
        image?: (number | null) | Media;
        /**
         * Remote (wiki) image while local media is pending.
         */
        imageUrl?: string | null;
        sources?:
          | {
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  endOfService?:
    | T
    | {
        date?: T;
        message?: T;
      };
  attribution?: T;
  social?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        background?: T;
      };
  featuredCharacters?: T;
  featuredWeapons?: T;
  featuredScenarios?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storyline_select".
 */
export interface StorylineSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  eras?:
    | T
    | {
        title?: T;
        period?: T;
        subtitle?: T;
        body?: T;
        characters?: T;
        scenarios?: T;
        factions?: T;
        image?: T;
        imageUrl?: T;
        sources?:
          | T
          | {
              url?: T;
              id?: T;
            };
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}